# Generated by Django 4.0.4 on 2022-06-04 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Navbat_buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('korxona_nomi', models.CharField(default='nimadir', max_length=340)),
                ('soha', models.CharField(default='soha', max_length=50)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('sana', models.DateField(default=django.utils.timezone.now)),
                ('meet_turi', models.CharField(choices=[('OFFLINE', 'OFFLINE'), ('ONLINE', 'ONLINE')], default='nimadir', max_length=30)),
                ('phone_number', models.IntegerField(default='0000', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post_foydalanuvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='uz', max_length=50)),
                ('user_idsi', models.IntegerField(null=True)),
                ('pul_turi', models.CharField(choices=[("SO'M", "SO'M"), ('YEVRO', 'YEVRO'), ('DOLLAR', 'DOLLAR')], default="So'm", max_length=10)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('narx', models.IntegerField(default='0000', null=True)),
                ('soha', models.CharField(choices=[('Stomotolog', 'stomotolog'), ('duxtir', 'duxtir')], default='Stomotolog', max_length=400)),
                ('qushimcha_malumot', models.TextField(default='Nima uzi bu soha')),
                ('rasm', models.ImageField(default='7459.jpg', upload_to='store')),
            ],
        ),
        migrations.CreateModel(
            name='Foydalanuvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='7459.jpg', upload_to='profile_pics')),
                ('location', models.CharField(default='Nomalum', max_length=300)),
                ('ish_vaqti', models.CharField(default='Nomalum', max_length=100)),
                ('korxona_haqida', models.TextField(default='Nomalum', max_length=1000)),
                ('phone', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
